### ISSUE TITLE
Regarding Login button

### ISSUE THREAD

**Issue by kartik9912** [Divisha-Gupta1/Final-Viva-#2]
Description:
The login button on the QuizMaster app is unresponsive. When users attempt to log in, nothing happens, and they are unable to access their accounts.

 When we Open the QuizMaster app and Navigate to the login screen.Enter the  valid login credentials (email and password).
Click the "Login" button. Upon clicking the "Login" button, the user should be authenticated and redirected to the main dashboard but Nothing happens when the "Login" button is clicked. The user remains on the login screen without any feedback or error message.

**Comment by Kavish2118** [comment]
done
